---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 5m0s
  targetNamespace: istio-system
