---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gateway
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m0s
  targetNamespace: istio-system
