---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: istiod
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m0s
  targetNamespace: istio-system
